name: task_distribution
description: "Robot Automation"

version: 1.2.6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.13.0
  provider: ^6.1.5+1
  window_manager: ^0.5.1
  http: ^1.6.0
  web_socket_channel: ^3.0.3
  file_picker: ^10.3.7
  path: ^1.9.0
  open_file: ^3.5.10
  local_notifier: ^0.1.6
  lottie: ^3.3.2
  url_launcher: ^6.3.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/