name: Build Windows Installer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.4'
          channel: 'stable'
          cache: true

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release --dart-define=domain=${{ secrets.DOMAIN }} --dart-define=https=true --obfuscate --split-debug-info=build/windows/debug_info

      # CÃ i Inno Setup
      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Download VC Redist (x64)
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vc14/vc_redist.x64.exe" -OutFile "VC_redist.x64.exe"
          Write-Host "Download VC Redist x64 completed."

      - name: Compile .ISS to .EXE
        run: iscc "setup.iss"

      - name: Release to GitHub
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: robot_${{ github.ref_name }}.exe
          file: Output/setup.exe
          tag: ${{ github.ref_name }}
          body: |
            ## ğŸš€ PhiÃªn báº£n ${{ github.ref_name }}
            
            ÄÃ¢y lÃ  báº£n cáº­p nháº­t má»›i nháº¥t cá»§a pháº§n má»m **Robot Automation**.
            
            ### ğŸ“¦ HÆ°á»›ng dáº«n cÃ i Ä‘áº·t
            1. Táº£i file setup **.exe** á»Ÿ pháº§n **Assets** bÃªn dÆ°á»›i.
            2. Cháº¡y file cÃ i Ä‘áº·t.
            3. Pháº§n má»m sáº½ tá»± Ä‘á»™ng kiá»ƒm tra vÃ  cÃ i Ä‘áº·t **Visual C++ Redistributable** náº¿u mÃ¡y báº¡n chÆ°a cÃ³.
            
            ### ğŸ“‹ YÃªu cáº§u há»‡ thá»‘ng
            * Há»‡ Ä‘iá»u hÃ nh: Windows 10/11 (x64)
            * Káº¿t ná»‘i Internet: Cáº§n thiáº¿t Ä‘á»ƒ táº£i tÃ i nguyÃªn láº§n Ä‘áº§u.
            
            ---
            *Báº£n build tá»± Ä‘á»™ng tá»« há»‡ thá»‘ng GitHub Actions.*
